apiVersion: v1
kind: Pod
metadata:
   name: pod-devops
spec:
   containers:
   - name: container-devops
     image: nginx:latest
     ports:
     - containerPort: 80
     volumeMounts:
     - mountPath: "/usr/share/nginx/html"
       name: storage-devops
   volumes:
   - name: storage-devops
     persistentVolumeClaim:
       claimName: pvc-devops
