apiVersion: v1
kind: Pod
metadata:
   name: nginx-phpfpm
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  - name: php-fpm-container
    image: php:7.2-fpm
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: shared-files
    emptyDir: {}
