apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  maxmemory: 2mb
vagrant@master-1:~/redis$ cat nodename.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis-container
        image: redis:alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: config-volume
      nodeName: worker-1
      volumes:
      - name: config-volume
        configMap:
          name: redis-config
      - name: data
        emptyDir: {}
